name: deploy
# 触发脚本的条件，develop分支push代码的时候
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/*
      # - __test__/** # dev 不需要立即测试
      - src/**
      - config/**

# 要执行的任务
jobs:
  # 任务名称
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境（必填）
    runs-on: ubuntu-latest
    # 任务步骤
    steps:
      # 获取源码
      - name: 迁出代码
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@master

      # 安装node
      - name: 安装node.js
        # 使用action库 actions/setup-node 安装node
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.3

      # 安装依赖
      - name: 安装依赖
        run: npm install

      # 打包
      - name: 打包
        run: npm run build

      # 上传打包文件到远程服务器
      - name: 发布
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.WFP_ID_RSA }}
          ARGS: '-avz --delete'
          SOURCE: 'dist/'
          REMOTE_HOST: '59.110.140.36'
          REMOTE_USER: 'work'
          TARGET: '/home/work/lightapp/app/manage' # 服务器目标路径
